def order_records(records):
    apply_order = [
        'order_time',
        'card_name',
        'order_id',
        'merchant_order_id',
        'pay_status',
        'order_amount',
        'paid_amount',
        'base_amount',
        'mw_apply_amount',
        'as_apply_amount',
        'top_up_amount',
        'mw_tx_fee',
        'as_tx_fee',
        'overpaid_amount',
        'order_currency',
        'transaction_hash',
        'sender_address',
        'receiver_address',
        'user_id',
        'card_id',
        'alias',
        'card_no',
        'cvv',
        'balance',
        'card_status',
        'currency',
        'email',
        'kyc_status',
        'order_data',
        'order_type',
        'order_status',
        'is_client'
    ]

    recharge_order = [
        'order_time',
        'card_name',
        'order_id',
        'merchant_order_id',
        'pay_status',
        'order_amount',
        'paid_amount',
        'recharge_amount',
        'mw_tx_fee',
        'as_tx_fee',
        'overpaid_amount',
        'order_currency',
        'transaction_hash',
        'sender_address',
        'receiver_address',
        'user_id',
        'order_card_id',
        'card_id',
        'alias',
        'card_no',
        'cvv',
        'balance',
        'card_status',
        'currency',
        'email',
        'kyc_status',
        'order_data',
        'order_type',
        'order_status',
        'is_client'
    ]

    underpaid_order = [
        'order_time',
        'card_name',
        'order_id',
        'merchant_order_id',
        'pay_status',
        'order_amount',
        'paid_amount',
        'base_amount',
        'underpaid_amount',
        'missing_amount',
        'order_currency',
        'transaction_hash',
        'sender_address',
        'receiver_address',
        'user_id',
        'order_card_id',
        'card_id',
        'alias',
        'card_no',
        'cvv',
        'balance',
        'card_status',
        'currency',
        'email',
        'kyc_status',
        'order_data',
        'order_type',
        'order_status',
        'is_client'
    ]

    ordered_apply_records = records['apply_records'][apply_order]
    ordered_recharge_records = records['recharge_records'][recharge_order]
    ordered_underpaid_records = records['underpaid_records'][underpaid_order]

    return {
        'apply_records': ordered_apply_records,
        'recharge_records': ordered_recharge_records,
        'underpaid_records': ordered_underpaid_records,
        'error_records': records['error_records'],
        'test_records': records['test_records'],
    }