apply_order = [
    'tx_id',
    'sender_address',
    'recipient_address',
    'order_amount_before_fee',
    'order_amount_after_fee',
    'paid_amount',
    'overpaid_amount',
    'apply_amount',
    'refund_amount',
    'top_up_amount',
    'top_up_commission',
    'coin_id',
    'order_type',
    'pay_status',
    'order_status',
    'create_time',
    'update_time',
    'refund_time',
    'expire_time',
    'closed_time',
    'order_data',
    'user_id',
    'kyc_status',
    'card_id',
    'name_on_card',
    'card_number',
    'card_status',
    'card_project',
    'active_date',
    'card_issuer',
]

recharge_order = [
    'tx_id',
    'sender_address',
    'recipient_address',
    'order_amount_before_fee',
    'order_amount_after_fee',
    'paid_amount',
    'overpaid_amount',
    'refund_amount',
    'top_up_amount',
    'top_up_commission',
    'coin_id',
    'order_type',
    'pay_status',
    'order_status',
    'create_time',
    'update_time',
    'refund_time',
    'expire_time',
    'closed_time',
    'order_data',
    'user_id',
    'kyc_status',
    'card_id',
    'name_on_card',
    'card_number',
    'card_status',
    'card_project',
    'active_date',
    'card_issuer',
]

test_order = [
    'tx_id',
    'sender_address',
    'recipient_address',
    'order_amount_before_fee',
    'order_amount_after_fee',
    'paid_amount',
    'refund_amount',
    'coin_id',
    'order_type',
    'pay_status',
    'order_status',
    'create_time',
    'update_time',
    'refund_time',
    'expire_time',
    'closed_time',
    'order_data',
    'user_id',
    'kyc_status',
    'card_id',
    'name_on_card',
    'card_number',
    'card_status',
    'card_project',
    'active_date',
    'card_issuer',
]


def order_records(records):
    records['apply'] = records['apply'] if records['apply'].empty else records['apply'][apply_order]
    records['recharge'] = records['recharge'] if records['recharge'].empty else records['recharge'][recharge_order]
    records['test'] = records['test'] if records['test'].empty else records['test'][test_order]

    return records
